TinyTurtle.apply(window);

function square(){
    forward(50);
    right(90);
    forward(50);
    right(90);
    forward(50);
    right(90);
    forward(50);
    right(90);
    forward(50);    }

function triangle(){
    right(60);
    forward(30);
    right(60);
    forward(30);
    right(60);
    right(120);
    forward(30);
    right(60);      }

function house(){
    forward(50);
    right(90);
    forward(50);
    right(90);
    forward(50);
    right(90);
    forward(50);
    right(90);
    forward(50);
    right(60);
    forward(30);
    right(60);
    forward(30);
    right(60);
    right(120);
    forward(30);
    right(60);      }

function pentagon(){
    right(72);
    forward(50);
    right(72);
    forward(50);
    right(72);
    forward(50);
    right(72);
    forward(50);
    right(72);
    forward(50);
    right(72);
    forward(50);    }

function hexagon(){
    right(60);
    forward(50);
    right(60);
    forward(50);
    right(60);
    forward(50);
    right(60);
    forward(50);
    right(60);
    forward(50);
    right(60);
    forward(50);    }
    
function circle(){
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);
    right(1); forward(1);   }

// Type your function call below
circle();

stamp();
